services:
  accommodation-app-db:
    image: postgres:17.5-alpine
    ports:
      - '35001:5432'
    restart: 'no'
    environment : 
      - POSTGRES_USER=accommodation-dev
      - POSTGRES_PASSWORD=CLI-825.2025X
      - POSTGRES_DB=accommodation-dev

    volumes:
      - accommodation-db:/var/lib/postgresql/data

volumes:
  accommodation-db:
    driver: local
