spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}

# Auth Service Configuration
auth:
  service:
    url: ${AUTH_SERVICE_URL:https://travel-apap-mock-server.vercel.app}

# Bill Service Configuration
bill:
  service:
    url: ${BILL_SERVICE_URL:http://localhost:8081}
    api-key: ${BILL_SERVICE_API_KEY:lalaleen}