spring:
  application:
    name : accommodation-be

  mvc:
    hiddenmethod : 
      filter :
        enabled : true

  profiles:
    active : 'dev'

  jpa : 
    hibernate :
      ddl-auto : create-drop

# Auth Service Configuration
auth:
  service:
    url: ${AUTH_SERVICE_URL:https://travel-apap-mock-server.vercel.app}

# Bill Service Configuration
bill:
  service:
    url: ${BILL_SERVICE_URL:http://2306275380-be.hafizmuh.site}
    api-key: ${BILL_SERVICE_API_KEY:lalaleen}