spring:
  application:
    name : accomodation-be

  mvc:
    hiddenmethod : 
      filter :
        enabled : true

  profiles:
    active : 'dev'

  jpa : 
    hibernate :
      ddl-auto : create-drop