apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accommodation-2306275600-be-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 2306275600-be.hafizmuh.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: accommodation-2306275600-be-service
                port:
                  number: 80